[book]
authors = ["Composer authors", "gemmaro"]
language = "ja"
multilingual = false
src = "translations/ja"
title = "Composer"

[output.html]
git-repository-url = "https://github.com/gemmaro/composer"
