#!/bin/sh

set -eu

changelog_path=$1
temporary_file=$(mktemp)

IFS=''
skip=no
while read -r line; do
    if [ $skip = "yes" ]; then
        case $line in
            [*)
                skip=no
                echo "$line" >> "$temporary_file"
        esac
    else
        case $line in
            "### [2.6.3] 2023-09-15")
                skip=yes
                ;;
            *)
                echo "$line" >> "$temporary_file"
        esac
    fi
done < "$changelog_path"

cp "$temporary_file" "$changelog_path"
